### ISSUE TITLE
sdtc:dischargeDispositionCode not being generated at proper location in Encounter segment.

### ISSUE THREAD

**Issue by syamat** [mdht/mdht-models#107] opened 2017-03-23 04:30 UTC
While trying to generate the QRDA Cat 1 file the "sdtc:dischargeDispositionCode" is being generated after the "entityRelationship" whereas it should be generated after the "effectiveTime" entry. Due to this the schema validation of the xml is failing.

I have attached the mdht library we are using as well as the generated xml.

Please provide some help in this regard.

[CMS26_NQF0338(5).zip](https://github.com/mdht/mdht-models/files/863607/CMS26_NQF0338.5.zip)

[mdht.zip](https://github.com/mdht/mdht-models/files/863603/mdht.zip)

**Comment by drbgfc** [comment] 2017-03-23 14:37
Thanks for posting the issue.
Can you first verify that the issue exists in the latest build here?
https://github.com/mdht/mdht-models/releases/tag/v2.6.2.20170118_Consol2

**Comment by syamat** [comment] 2017-03-24 04:08
The issue exists in the latest build as well. I am attaching the library and the generated xmls.
[mdht.zip](https://github.com/mdht/mdht-models/files/866851/mdht.zip)
[CMS26_NQF0338.zip](https://github.com/mdht/mdht-models/files/866854/CMS26_NQF0338.zip)

**Comment by drbgfc** [comment] 2017-03-24 14:05
Ok - can you also attach the source code you are using to generate?
I wonder if the same issue happens when generating a basic C-CDA R2.1 file.

**Comment by syamat** [comment] 2017-03-25 10:25
public static void create(ContinuityOfCareDocument2 cd, Section patientDataSection,QRDAModel qrdaModel,Encounter encounterModel,org.eclipse.mdht.uml.cda.Encounter encounter, Date docDate,String valueSet)
	{
		try {
			
			encounter.setClassCode(ActClass.ENC);
			encounter.setMoodCode(x_DocumentEncounterMood.EVN);	
			encounter.getTemplateIds().add(DatatypesFactory.eINSTANCE.createII("2.16.840.1.113883.10.20.22.4.49","2015-08-01"));
			encounter.getTemplateIds().add(DatatypesFactory.eINSTANCE.createII("2.16.840.1.113883.10.20.24.3.23","2016-02-01"));
			encounter.getIds().add(DatatypesFactory.eINSTANCE.createII("2.16.840.1.113883.3.3619.99.7","Inpatient999"));
			 
			encounter.setCode(DatatypesFactory.eINSTANCE.createCD("32485007", "2.16.840.1.113883.6.96", "SNOMED-CT", ""));
			encounter.setText(DatatypesFactory.eINSTANCE.createED("Inpatient Encounter");
			encounter.setStatusCode(DatatypesFactory.eINSTANCE.createCS("completed"));
			encounter.setEffectiveTime(EffectiveTimeSegment.createIVLTSEffectiveTime("20150101000000+0530", "20151231000000+0530"));
			
			encounter.getSDTCDischargeDispositionCodes().add( DatatypesFactory.eINSTANCE.createCE("10161009", "2.16.840.1.113883.6.96", "SNOMED-CT", null);
			
			
			
			
			if(null != encounterModel.getPrincipalDiagnosisList()){
				EntryRelationship entryRelationship = CDAFactory.eINSTANCE.createEntryRelationship();
				entryRelationship.setTypeCode(x_ActRelationshipEntryRelationship.REFR);
				org.eclipse.mdht.uml.cda.Observation observation=CDAFactory.eINSTANCE.createObservation();
				
				encounter.getEntryRelationships().add(entryRelationship);
				observation.setClassCode(ActClassObservation.OBS);
				observation.setMoodCode(x_ActMoodDocumentObservation.EVN);
				observation.setCode(DatatypesFactory.eINSTANCE.createCD("8319008", "2.16.840.1.113883.6.96","SNOMED-CT", "Principal Diagnosis"));
				observation.getValues().add(DatatypesFactory.eINSTANCE.createCD("707980005", "2.16.840.1.113883.6.96", "SNOMED-CT", null);
				
				entryRelationship.setObservation(observation);
				
			}
			
			
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

**Comment by drbgfc** [comment] 2017-03-27 14:57
I reproduced the issue by modifying a pass test in EncounterActivitiesTest.java (adding an entryRelationship) - did not save this change:

	@Test
	public void testValidateEncounterActivitiesSdtcDDCFromNUBCOrDD() {

...

```java
				addPassTest(new PassTest() {
					@Override
					public void updateToPass(EncounterActivities target) {
						target.init();
						target.addAct(ConsolFactory.eINSTANCE.createEncounterDiagnosis().init());
						CE sdtcCode = DatatypesFactory.eINSTANCE.createCE();
						sdtcCode.setCode("notChecked"); // Required to be defined, but not to any specific String
						sdtcCode.setCodeSystem(NUBC_CODESYSTEM_VALUE); // the actual constraint checked which must be accurate
						sdtcCode.setCodeSystemName("NUBC UB-04 FL17-Patient Status"); // not required (not checked as a constraint)
						target.getSDTCDischargeDispositionCodes().add(sdtcCode);
					}
				});
```

This produced this XML:
```xml
<encounter xmlns="urn:hl7-org:v3" xmlns:sdtc="urn:hl7-org:sdtc" classCode="ENC" moodCode="EVN">
  <templateId root="2.16.840.1.113883.10.20.22.4.49"/>
  <code codeSystem="2.16.840.1.113883.6.12" codeSystemName="CPT-4"/>
  <entryRelationship>
    <act classCode="ACT" moodCode="EVN">
      <templateId root="2.16.840.1.113883.10.20.22.4.80"/>
      <code code="29308-4" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Diagnosis"/>
    </act>
  </entryRelationship>
  <sdtc:dischargeDispositionCode code="notChecked" codeSystem="2.16.840.1.113883.6.301.5" codeSystemName="NUBC UB-04 FL17-Patient Status"/>
</encounter>
```

So the issue is in Consol2 (mdl) or CDA (mdl) or the plugins.

Here is a snip from CDA (mdl):
![image](https://cloud.githubusercontent.com/assets/5495334/24362853/09cd66fe-12dc-11e7-8869-3e88de6a13f3.png)

Any thoughts Sean?

**Comment by swmuir** [comment] 2017-03-27 18:27
It appears the physical order is not correct - i will update the core model and regenerate the code base -

**Comment by syamat** [comment] 2017-04-03 07:10
Hi Sean, When can I expect a fix for the problem.

**Comment by swmuir** [comment] 2017-04-03 17:48
i will work with dan on getting this included in the april release 

we will probable have an eclipse release before that

thanks

Sean

**Comment by swmuir** [comment] 2017-04-27 17:39
Updated the model and merged update to develop branch - this will be part of the May release

**Closed by swmuir** 2017-04-27 17:39 UTC
